server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
        expires 1m;
        add_header Cache-Control "public, max-age=60";
    }

    # Datos JSON generados por el collector
    location /data/ {
        alias /data/json/;
        expires -1;
        add_header Cache-Control "no-store";
    }

    access_log /var/log/nginx/meshtastic-es-map_access.log;
    error_log  /var/log/nginx/meshtastic-es-map_error.log;
}
